version: '3.8'

services:
  web:
    container_name: order-product-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NITRO_PORT=3000
      - NITRO_HOST=0.0.0.0
      - VITE_API_ENDPOINT=http://localhost:3001/
    command: ["npm", "run", "start"]
